### PR TITLE
Allow user to specify the image of privileged container

### PR DESCRIPTION
**Pull request by topikachu**
This change let the tool to run with a private registry

### CODE REVIEW

**Comment by eldadru** [comment]
Hi @topikachu - thanks for taking the time and submitting this PR, sorry for my (very) late response
everything looks good, please increase the version to 1.3.3

**Comment by topikachu** [comment]
@eldadru 1.3.3 is already tagged. Shall I increase to 1.3.4?

**Comment by topikachu** [comment]
Rebase on the latest master.
Increase version to 1.3.4.
All are green now.

**Comment by eldadru** [comment]
@topikachu great, thanks!

**Pull request merged**
