### PR TITLE
Support containerd runtime

### LINKED ISSUE #65: Using ksniff on microk8s (containerd container runtime)
Hi,

I've had ksniff working with a minikube deployment with no issues. I've switched to microk8s and am now getting the following error.

`ERRO[0000] failed to create privileged pod on node: 'mudged-laptop'  error="container runtime on node: 'mudged-laptop' isn't docker"`

From what I can see this is down to microk8s using containerd as the container runtime.

Firstly am I right in my assumption? And are there any plans to support microk8s/containerd in the future?

### PR DESCRIPTION
**Pull request by SeMeKh**
Fixes #65

### CODE REVIEW

**Comment by bostrt** [comment]
Hi @SeMeKh I'll take a look at this after https://github.com/eldadru/ksniff/pull/90 is merged.

**Comment by SeMeKh** [comment]
@bostrt I think it does. Already tried creating a container through the containerd socket using `ctr` and it doesn't work. So the `chroot` is needed.
May I ask about the intention behind dropping the `/host` mount?

**Comment by bostrt** [comment]
>  May I ask about the intention behind dropping the /host mount?

Certainly! @SeMeKh its based around conversation in https://github.com/eldadru/ksniff/pull/90.

**Comment by bostrt** [comment]
@SeMeKh would [crictl](https://github.com/kubernetes-sigs/cri-tools) work with containerd or do you have to use `ctr`? Unfortunately, I'm not very familiar with inner workings of containerd.

**Comment by namco1992** [comment]
Hello @SeMeKh @bostrt, AFAIK, both the CRI-O and containerd implements the CRI. I believe that we should be able to achieve most of the things - if not all - with `crictl` in both of the runtimes (see [here](https://kubernetes.io/docs/tasks/debug-application-cluster/crictl/#create-a-container)). In fact, the crictl will [try to connect to containerd socket by default](https://github.com/kubernetes-sigs/cri-tools/blob/master/docs/crictl.md#usage).
 Is it possible that reusing the `crictl` image we discussed in #90 for both CRI-O and containerd runtimes? I just put in my two cents here and pls correct me if I'm wrong. Thanks!

**Comment by SeMeKh** [comment]
@namco1992 That was what I was aiming for at first, and would be great if possible, since that would make it compatible to almost any runtime. Trying to implement it though, I realized that when I used the CRI to add a new container to the existing pod, `kubelet` detected it as a deviation from desired state and got rid of it. I didn't really push it anymore though, I might've had missed something.

**Comment by namco1992** [comment]
> @namco1992 That was what I was aiming for at first, and would be great if possible, since that would make it compatible to almost any runtime. Trying to implement it though, I realized that when I used the CRI to add a new container to the existing pod, `kubelet` detected it as a deviation from desired state and got rid of it. I didn't really push it anymore though, I might've had missed something.

It seems to be an expected behaviour according to this [issue](https://github.com/containerd/cri/issues/520#issuecomment-355362760).

However, on second thought, it seems to be inevitable to mount the host path. Initially I against the idea due to security reasons, but I didn't know enough about other runtimes other than docker and I didn't see the necessity of mounting the host root path (or `chroot`).

One of the main concern I have is that the compatibility between all those cmd line tools. If we go for the solution that building a util container with crictl/ctr/etc. installed, we might end up maintaining quite a few versions of them for different k8s versions/distro/etc. Under this circumstance, calling the host `ctl` with `chroot` seems to be more reasonable and robust.

Here are my suggestions:
1. I refactor my PR https://github.com/eldadru/ksniff/pull/90 to mount the `/host` path **AND** the socket. This could solve the issue that https://github.com/eldadru/ksniff/pull/90 originally targets at;
2. All other places where having dependencies on `/host` path should remain the same.

@SeMeKh @bostrt WDYT?

**Comment by SeMeKh** [comment]
I don't think mounting `/host` in the `ksniff` pod is much different from passing in the socket securitywise, since one with the socket could just run a privileged container with arbitrary mounts. Given that, I think keeping the `/host` mount is the only way to go.

Regarding #90 though, I'd suggest allowing passing in extra runtime-specific options as cli arguments. This could be some general-purpose flag like `--runtime-opts` or something more runtime-aware like `--docker-socket`/`--containerd-socket`/`--containerd-namespace`. That way the runtime can customize its behavior accordingly.

**Comment by bostrt** [comment]
Agreed, any risk associated with mounting `/host` is still there with using a privileged container (though appearances would be better). I think the trade-off of creating many more util-type container images would but worse for maintenance and security. 

I'm for keeping `/host`. 

In the future, we can investigate moving the privileged Pod creation into the container runtime implementation code if needed if some other runtime needs extra special treatment.

> I refactor my PR #90 to mount the /host path AND the socket. This could solve the issue that #90 originally targets at;
> All other places where having dependencies on /host path should remain the same.

Yes, I'm good with this. I'll be curious to see how mounting both works, but we can continue conversation on #90 regarding that.

**Comment by bostrt** [comment]
Hey @SeMeKh we've kept the `/host` mount! 

The PR we spoke about earlier has been merged and now there is a conflict in your PR. Would you mind addressing that and updating your PR please?

**Comment by SeMeKh** [comment]
@bostrt Thanks for the update. I've rebased and tested the code. Should be mergeable.

**Comment by bostrt** [comment]
Hi @SeMeKh, I'll test this myself in a microk8s environment soon and follow-up.

I see there's a new helper container image being used (`docker.io/hamravesh/ksniff-helper:v3`). Would you mind updating the Docker page with the link to your source repository for the image?

**Comment by SeMeKh** [comment]
@bostrt Added. It might be a good idea to build these images on ksniff itself, maybe?

**Comment by bostrt** [comment]
@SeMeKh I'm not sure I follow. Do you mean putting them in a GitHub group?

**Comment by SeMeKh** [comment]
@bostrt Nope. Just thought it might be a good idea to have a single `ksniff-helper` image with different tags rather than having those images scattered in different repositories owned by different people. If it looks good to you, could send a separate PR for that as well.

**Comment by bostrt** [comment]
Hi @SeMeKh I see and I think that makes sense. We now have at least 3 images:

- tcpdump
- containerd
- docker

If you don't mind submitting a PR for this, I'm happy to review and we should pull in @eldadru to comment; this would be a significant change.

**Comment by SeMeKh** [comment]
@bostrt I'd be more than happy to send a PR. But I'm a bit busy lately. Can we have this PR merged and have that refactoring later on?

**Comment by SeMeKh** [comment]
@bostrt Friendly ping.

**Comment by stefanhenseler** [comment]
@bostrt  do you have a timeline for when this will be merged? I'm currently using the branch from @SeMeKh and works great on GKE so far.

**Comment by bostrt** [comment]
Hi!  Sorry for the late reply. I will be able to get to it this week.

**Comment by stefanhenseler** [comment]
@bostrt  Hey, no worries :) Just wanted to ask if this will be merged and released anytime soon. Thanks for your work!

**Comment by bostrt** [comment]
My only concern at this point is, will this work with k3s' containerd (i don't think so) and is that a use case we want to support at this time. @eldadru wdyt?

**Comment by SeMeKh** [comment]
@bostrt it does work on k3s too. I've tested on that as well. You might need to pass in `--socket` for different deployments, `/run/k3s/containerd/containerd.sock` in case of k3s.

**Comment by bostrt** [comment]
Apologies on the delay again. Busy with my day-job :) 

After using your suggestion, it works great with k3s!

I've been trying to test on microk8s but its not working out: 

```
$ ./kubectl-sniff -n test -p mypod --socket /var/snap/microk8s/common/run/containerd.sock
...
INFO[0007] pod: 'ksniff-kfr7v' created successfully on node: 'rbost' 
INFO[0007] spawning wireshark!                          
INFO[0007] starting remote sniffing using privileged pod 
INFO[0007] executing command: '[/bin/sh -c 
    set -ex
    export CONTAINERD_SOCKET="/var/snap/microk8s/common/run/containerd.sock"
    export CONTAINERD_NAMESPACE="k8s.io"
    export CONTAINER_RUNTIME_ENDPOINT="unix:///host${CONTAINERD_SOCKET}"
    export IMAGE_SERVICE_ENDPOINT=${CONTAINER_RUNTIME_ENDPOINT}
    crictl pull docker.io/maintained/tcpdump:latest >/dev/null
    netns=$(crictl inspect 42b33ac14e47377efa83ecfb0719748c14e10f712713fb0bbcd4e92680f479fd | jq '.info.runtimeSpec.linux.namespaces[] | select(.type == "network") | .path' | tr -d '"')
    exec chroot /host ctr -a ${CONTAINERD_SOCKET} run --rm --with-ns "network:${netns}" docker.io/maintained/tcpdump:latest ksniff-container-SVjrZoCw tcpdump -i any -U -w -  
    ]' on container: 'ksniff-privileged', pod: 'ksniff-kfr7v', namespace: 'test' 
ERRO[0009] failed executing command: '[/bin/sh -c 
    set -ex
    export CONTAINERD_SOCKET="/var/snap/microk8s/common/run/containerd.sock"
    export CONTAINERD_NAMESPACE="k8s.io"
    export CONTAINER_RUNTIME_ENDPOINT="unix:///host${CONTAINERD_SOCKET}"
    export IMAGE_SERVICE_ENDPOINT=${CONTAINER_RUNTIME_ENDPOINT}
    crictl pull docker.io/maintained/tcpdump:latest >/dev/null
    netns=$(crictl inspect 42b33ac14e47377efa83ecfb0719748c14e10f712713fb0bbcd4e92680f479fd | jq '.info.runtimeSpec.linux.namespaces[] | select(.type == "network") | .path' | tr -d '"')
    exec chroot /host ctr -a ${CONTAINERD_SOCKET} run --rm --with-ns "network:${netns}" docker.io/maintained/tcpdump:latest ksniff-container-SVjrZoCw tcpdump -i any -U -w -  
    ]', exitCode: '127', stdErr: '+ export 'CONTAINERD_SOCKET=/var/snap/microk8s/common/run/containerd.sock'
+ export 'CONTAINERD_NAMESPACE=k8s.io'
+ export 'CONTAINER_RUNTIME_ENDPOINT=unix:///host/var/snap/microk8s/common/run/containerd.sock'
+ export 'IMAGE_SERVICE_ENDPOINT=unix:///host/var/snap/microk8s/common/run/containerd.sock'
+ crictl pull docker.io/maintained/tcpdump:latest
+ crictl inspect 42b33ac14e47377efa83ecfb0719748c14e10f712713fb0bbcd4e92680f479fd
+ jq '.info.runtimeSpec.linux.namespaces[] | select(.type == "network") | .path'
+ tr -d '"'
+ netns=/proc/13017/ns/net
+ exec chroot /host ctr -a /var/snap/microk8s/common/run/containerd.sock run --rm --with-ns network:/proc/13017/ns/net docker.io/maintained/tcpdump:latest ksniff-container-SVjrZoCw tcpdump -i any -U -w -
chroot: can't execute 'ctr': No such file or directory
'  error="command terminated with exit code 127"
ERRO[0009] failed to start sniffing using privileged pod, exit code: '127'  error="command terminated with exit code 127"
ERRO[0009] failed to start remote sniffing, stopping wireshark  error="command terminated with exit code 127"
INFO[0009] starting sniffer cleanup                     
INFO[0009] removing privileged container: ''            
INFO[0009] executing command: '[/bin/sh -c 
    set -ex
    export CONTAINERD_SOCKET="/var/snap/microk8s/common/run/containerd.sock"
    export CONTAINERD_NAMESPACE="k8s.io"
    export CONTAINER_ID="ksniff-container-SVjrZoCw"
    chroot /host ctr -a ${CONTAINERD_SOCKET} task kill -s SIGKILL ${CONTAINER_ID}
    ]' on container: 'ksniff-privileged', pod: 'ksniff-kfr7v', namespace: 'test' 
ERRO[0009] failed executing command: '[/bin/sh -c 
    set -ex
    export CONTAINERD_SOCKET="/var/snap/microk8s/common/run/containerd.sock"
    export CONTAINERD_NAMESPACE="k8s.io"
    export CONTAINER_ID="ksniff-container-SVjrZoCw"
    chroot /host ctr -a ${CONTAINERD_SOCKET} task kill -s SIGKILL ${CONTAINER_ID}
    ]', exitCode: '127', stdErr: '+ export 'CONTAINERD_SOCKET=/var/snap/microk8s/common/run/containerd.sock'
+ export 'CONTAINERD_NAMESPACE=k8s.io'
+ export 'CONTAINER_ID=ksniff-container-SVjrZoCw'
+ chroot /host ctr -a /var/snap/microk8s/common/run/containerd.sock task kill -s SIGKILL ksniff-container-SVjrZoCw
chroot: can't execute 'ctr': No such file or directory
'  error="command terminated with exit code 127"
ERRO[0009] failed to remove privileged container: '', exit code: '127', please manually remove it  error="command terminated with exit code 127"
INFO[0009] removing pod: 'ksniff-kfr7v'                 
INFO[0009] removing privileged pod: 'ksniff-kfr7v'      
INFO[0009] privileged pod: 'ksniff-kfr7v' removed       
INFO[0009] pod: 'ksniff-kfr7v' removed successfully     
INFO[0009] sniffer cleanup completed successfully       
Error: signal: killed
```

**Comment by bostrt** [comment]
When I force `containerd.go` to use `/snap/bin/microk8s.ctr` (bypassing the command issue in previous comment), its failing with something much more peculiar:

```
+ exec chroot /host /snap/bin/microk8s.ctr -a /var/snap/microk8s/common/run/containerd.sock run --rm --with-ns network:/proc/29901/ns/net docker.io/maintained/tcpdump:latest ksniff-container-kYbHhpSW tcpdump -i any -U -w -
sudo: unable to resolve host ksniff-xfjn6: Temporary failure in name resolution
ctr: Cannot use two forms of the same flag: a address
'  error="command terminated with exit code 1"
```

At this point, I'm happy merging this since it supports k3s and apparently GKE without any issues. We can address microk8s later; it seems finicky anyways.  What do you think @SeMeKh? 

@stefanhenseler would you mind uploading some of the CLI output from ksniff when you are using it with GKE just so we can have a record of it?

**Comment by SeMeKh** [comment]
@bostrt Sure, sounds like a plan. I can look into microk8s later on.

**Comment by bostrt** [comment]
@SeMeKh thanks again for all of the help and patience

**Pull request merged**
