### PR TITLE
support Apple Silicon M1

### LINKED ISSUE #134: Support Apple Silicon M1
Hi all, I'm using macOS for my daily working. It seems ksniff needs support Armv64 architecture in Apple M1.

I have contributed a PR which supported M1 in release stage.

### PR DESCRIPTION
**Pull request by fenngwd**
Fixes #134

### CODE REVIEW

**Comment by frankgu968** [comment]
Any updates on this improvement? Being able to use Ksniff on the M1s will be very handy!

**Comment by 2ZZ** [comment]
I would also appreciate this

**Comment by MXfive** [comment]
This has been idle for a very long time, is there any help needed in maintaining and getting things like this merged?

**Comment by fenngwd** [comment]
@bostrt Please have a look at this PR, it has been submitted for a long time.

**Comment by fenngwd** [comment]
@bostrt It seems I can't assign this PR to you.
image

**Pull request merged**
